use crate::store::report_store::{ReportError, TimeRangeKind};

// ----------------------------------------------------------------
// Rendered data types — produced by engine, consumed by renderer
// ----------------------------------------------------------------

pub struct SummaryRow {
    pub label: String,
    pub device_id: String,
    pub point_id: String,
    pub min: f64,
    pub max: f64,
    pub avg: f64,
    pub sample_count: usize,
}

pub struct RuntimeRow {
    pub label: String,
    pub device_id: String,
    pub point_id: String,
    pub on_percent: f64,
    pub total_hours: f64,
    pub on_hours: f64,
}

pub struct AlarmEventRow {
    pub timestamp_ms: i64,
    pub device_id: String,
    pub point_id: String,
    pub severity: String,
    pub from_state: String,
    pub to_state: String,
    pub value: f64,
}

pub struct CurrentValueRow {
    pub label: String,
    pub device_id: String,
    pub point_id: String,
    pub value: f64,
    pub status: String,
}

pub struct SeverityCount {
    pub name: String,
    pub count: usize,
}

pub struct TypeCount {
    pub name: String,
    pub count: usize,
}

pub enum RenderedSection {
    HistorySummary {
        title: String,
        rows: Vec<SummaryRow>,
    },
    AlarmSummary {
        title: String,
        by_severity: Vec<SeverityCount>,
        by_type: Vec<TypeCount>,
        total: usize,
    },
    AlarmList {
        title: String,
        events: Vec<AlarmEventRow>,
    },
    CurrentValues {
        title: String,
        rows: Vec<CurrentValueRow>,
    },
    RuntimeSummary {
        title: String,
        rows: Vec<RuntimeRow>,
    },
    EnergyConsumption {
        title: String,
        rows: Vec<EnergyRow>,
    },
    DemandSummary {
        title: String,
        rows: Vec<DemandRow>,
    },
}

#[derive(Debug, Clone)]
pub struct EnergyRow {
    pub label: String,
    pub consumption_kwh: f64,
    pub peak_kw: f64,
    pub avg_kw: f64,
    pub cost: f64,
}

#[derive(Debug, Clone)]
pub struct DemandRow {
    pub label: String,
    pub peak_kw: f64,
    pub peak_time_ms: i64,
    pub load_factor: f64,
}

// ----------------------------------------------------------------
// HTML rendering — inline CSS for email compatibility
// ----------------------------------------------------------------

/// Render a complete report to self-contained HTML with inline CSS.
pub fn render_report_html(
    title: &str,
    start_ms: i64,
    end_ms: i64,
    time_range: &TimeRangeKind,
    sections: &[RenderedSection],
) -> Result<String, ReportError> {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as i64;

    let mut html = String::with_capacity(8192);

    // Document start
    html.push_str("<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n");
    html.push_str(&format!("<title>{}</title>\n", escape_html(title)));
    html.push_str("</head>\n");
    html.push_str(&format!(
        "<body style=\"{}\">\n",
        "margin:0;padding:0;background:#1a1a2e;color:#e0e0e0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:14px;line-height:1.5"
    ));

    // Container
    html.push_str("<div style=\"max-width:800px;margin:0 auto;padding:24px;\">\n");

    // Header
    html.push_str(&format!(
        "<div style=\"{}\">\n",
        "background:#16213e;border-radius:8px;padding:24px;margin-bottom:24px;border:1px solid #2a2a4a"
    ));
    html.push_str(&format!(
        "<h1 style=\"margin:0 0 8px 0;font-size:22px;color:#f0f0f0;\">{}</h1>\n",
        escape_html(title)
    ));
    html.push_str(&format!(
        "<p style=\"margin:0;color:#a0a0b0;font-size:13px;\">Period: {} &mdash; {} to {}</p>\n",
        escape_html(time_range.label()),
        format_datetime(start_ms),
        format_datetime(end_ms),
    ));
    html.push_str(&format!(
        "<p style=\"margin:4px 0 0 0;color:#808090;font-size:12px;\">Generated: {}</p>\n",
        format_datetime(now),
    ));
    html.push_str("</div>\n");

    // Sections
    for section in sections {
        render_section(&mut html, section);
    }

    // Footer
    html.push_str(&format!(
        "<div style=\"{}\">\n",
        "margin-top:32px;padding-top:16px;border-top:1px solid #2a2a4a;text-align:center;color:#606070;font-size:12px"
    ));
    html.push_str("Generated by OpenCrate BMS\n</div>\n");

    // Close
    html.push_str("</div>\n</body>\n</html>");

    Ok(html)
}

fn render_section(html: &mut String, section: &RenderedSection) {
    match section {
        RenderedSection::HistorySummary { title, rows } => {
            render_section_header(html, title);
            if rows.is_empty() {
                render_empty(
                    html,
                    "No history data available for the selected points and time range.",
                );
                return;
            }
            html.push_str(&format!("<table style=\"{}\">\n", TABLE_STYLE));
            html.push_str("<tr>");
            for h in &["Point", "Min", "Max", "Avg", "Samples"] {
                html.push_str(&format!("<th style=\"{}\">{}</th>", TH_STYLE, h));
            }
            html.push_str("</tr>\n");
            for (i, row) in rows.iter().enumerate() {
                let bg = if i % 2 == 0 { ROW_EVEN } else { ROW_ODD };
                html.push_str(&format!("<tr style=\"background:{bg}\">"));
                html.push_str(&format!(
                    "<td style=\"{}\">{}</td>",
                    TD_STYLE,
                    escape_html(&row.label)
                ));
                html.push_str(&format!(
                    "<td style=\"{}{}\">",
                    TD_STYLE, "text-align:right;"
                ));
                html.push_str(&format!("{:.2}</td>", row.min));
                html.push_str(&format!(
                    "<td style=\"{}{}\">",
                    TD_STYLE, "text-align:right;"
                ));
                html.push_str(&format!("{:.2}</td>", row.max));
                html.push_str(&format!(
                    "<td style=\"{}{}\">",
                    TD_STYLE, "text-align:right;"
                ));
                html.push_str(&format!("{:.2}</td>", row.avg));
                html.push_str(&format!(
                    "<td style=\"{}{}\">",
                    TD_STYLE, "text-align:right;"
                ));
                html.push_str(&format!("{}</td>", row.sample_count));
                html.push_str("</tr>\n");
            }
            html.push_str("</table>\n</div>\n");
        }

        RenderedSection::AlarmSummary {
            title,
            by_severity,
            by_type,
            total,
        } => {
            render_section_header(html, title);
            html.push_str(&format!(
                "<p style=\"color:#a0a0b0;margin:0 0 12px 0;\">Total alarm events: <strong style=\"color:#f0f0f0;\">{total}</strong></p>\n"
            ));

            if !by_severity.is_empty() {
                html.push_str("<p style=\"color:#c0c0d0;margin:8px 0 4px 0;font-weight:600;\">By Severity</p>\n");
                html.push_str(&format!("<table style=\"{}\">\n", TABLE_STYLE));
                html.push_str(&format!("<tr><th style=\"{}\">Severity</th><th style=\"{}text-align:right;\">Count</th></tr>\n", TH_STYLE, TH_STYLE));
                for (i, sc) in by_severity.iter().enumerate() {
                    let bg = if i % 2 == 0 { ROW_EVEN } else { ROW_ODD };
                    let color = severity_color(&sc.name);
                    html.push_str(&format!(
                        "<tr style=\"background:{bg}\"><td style=\"{}\"><span style=\"color:{color};\">{}</span></td><td style=\"{}text-align:right;\">{}</td></tr>\n",
                        TD_STYLE, escape_html(&sc.name), TD_STYLE, sc.count,
                    ));
                }
                html.push_str("</table>\n");
            }

            if !by_type.is_empty() {
                html.push_str("<p style=\"color:#c0c0d0;margin:16px 0 4px 0;font-weight:600;\">By Transition</p>\n");
                html.push_str(&format!("<table style=\"{}\">\n", TABLE_STYLE));
                html.push_str(&format!("<tr><th style=\"{}\">State</th><th style=\"{}text-align:right;\">Count</th></tr>\n", TH_STYLE, TH_STYLE));
                for (i, tc) in by_type.iter().enumerate() {
                    let bg = if i % 2 == 0 { ROW_EVEN } else { ROW_ODD };
                    html.push_str(&format!(
                        "<tr style=\"background:{bg}\"><td style=\"{}\">{}</td><td style=\"{}text-align:right;\">{}</td></tr>\n",
                        TD_STYLE, escape_html(&tc.name), TD_STYLE, tc.count,
                    ));
                }
                html.push_str("</table>\n");
            }
            html.push_str("</div>\n");
        }

        RenderedSection::AlarmList { title, events } => {
            render_section_header(html, title);
            if events.is_empty() {
                render_empty(html, "No alarm events in the selected time range.");
                return;
            }
            html.push_str(&format!("<table style=\"{}\">\n", TABLE_STYLE));
            html.push_str("<tr>");
            for h in &["Time", "Device", "Point", "Severity", "Transition", "Value"] {
                html.push_str(&format!("<th style=\"{}\">{}</th>", TH_STYLE, h));
            }
            html.push_str("</tr>\n");
            for (i, ev) in events.iter().enumerate() {
                let bg = if i % 2 == 0 { ROW_EVEN } else { ROW_ODD };
                let color = severity_color(&ev.severity);
                html.push_str(&format!("<tr style=\"background:{bg}\">"));
                html.push_str(&format!(
                    "<td style=\"{}white-space:nowrap;\">{}</td>",
                    TD_STYLE,
                    format_datetime(ev.timestamp_ms)
                ));
                html.push_str(&format!(
                    "<td style=\"{}\">{}</td>",
                    TD_STYLE,
                    escape_html(&ev.device_id)
                ));
                html.push_str(&format!(
                    "<td style=\"{}\">{}</td>",
                    TD_STYLE,
                    escape_html(&ev.point_id)
                ));
                html.push_str(&format!(
                    "<td style=\"{}\"><span style=\"color:{color};\">{}</span></td>",
                    TD_STYLE,
                    escape_html(&ev.severity)
                ));
                html.push_str(&format!(
                    "<td style=\"{}\">{} → {}</td>",
                    TD_STYLE,
                    escape_html(&ev.from_state),
                    escape_html(&ev.to_state)
                ));
                html.push_str(&format!(
                    "<td style=\"{}text-align:right;\">{:.2}</td>",
                    TD_STYLE, ev.value
                ));
                html.push_str("</tr>\n");
            }
            html.push_str("</table>\n</div>\n");
        }

        RenderedSection::CurrentValues { title, rows } => {
            render_section_header(html, title);
            if rows.is_empty() {
                render_empty(html, "No current values available.");
                return;
            }
            html.push_str(&format!("<table style=\"{}\">\n", TABLE_STYLE));
            html.push_str("<tr>");
            for h in &["Point", "Value", "Status"] {
                html.push_str(&format!("<th style=\"{}\">{}</th>", TH_STYLE, h));
            }
            html.push_str("</tr>\n");
            for (i, row) in rows.iter().enumerate() {
                let bg = if i % 2 == 0 { ROW_EVEN } else { ROW_ODD };
                html.push_str(&format!("<tr style=\"background:{bg}\">"));
                html.push_str(&format!(
                    "<td style=\"{}\">{}</td>",
                    TD_STYLE,
                    escape_html(&row.label)
                ));
                html.push_str(&format!(
                    "<td style=\"{}text-align:right;\">{:.2}</td>",
                    TD_STYLE, row.value
                ));
                html.push_str(&format!(
                    "<td style=\"{}\">{}</td>",
                    TD_STYLE,
                    escape_html(&row.status)
                ));
                html.push_str("</tr>\n");
            }
            html.push_str("</table>\n</div>\n");
        }

        RenderedSection::RuntimeSummary { title, rows } => {
            render_section_header(html, title);
            if rows.is_empty() {
                render_empty(html, "No runtime data available.");
                return;
            }
            html.push_str(&format!("<table style=\"{}\">\n", TABLE_STYLE));
            html.push_str("<tr>");
            for h in &["Equipment", "On %", "On Hours", "Total Hours"] {
                html.push_str(&format!("<th style=\"{}\">{}</th>", TH_STYLE, h));
            }
            html.push_str("</tr>\n");
            for (i, row) in rows.iter().enumerate() {
                let bg = if i % 2 == 0 { ROW_EVEN } else { ROW_ODD };
                let bar_color = if row.on_percent > 90.0 {
                    "#c0392b"
                } else if row.on_percent > 50.0 {
                    "#e67e22"
                } else {
                    "#27ae60"
                };
                html.push_str(&format!("<tr style=\"background:{bg}\">"));
                html.push_str(&format!(
                    "<td style=\"{}\">{}</td>",
                    TD_STYLE,
                    escape_html(&row.label)
                ));
                html.push_str(&format!(
                    "<td style=\"{}text-align:right;\"><span style=\"color:{bar_color};font-weight:600;\">{:.1}%</span></td>",
                    TD_STYLE, row.on_percent,
                ));
                html.push_str(&format!(
                    "<td style=\"{}text-align:right;\">{:.1}</td>",
                    TD_STYLE, row.on_hours
                ));
                html.push_str(&format!(
                    "<td style=\"{}text-align:right;\">{:.1}</td>",
                    TD_STYLE, row.total_hours
                ));
                html.push_str("</tr>\n");
            }
            html.push_str("</table>\n</div>\n");
        }

        RenderedSection::EnergyConsumption { title, rows } => {
            render_section_header(html, title);
            if rows.is_empty() {
                render_empty(html, "No energy data available.");
                return;
            }
            html.push_str(&format!("<table style=\"{}\">\n", TABLE_STYLE));
            html.push_str("<tr>");
            for h in &["Meter", "kWh", "Peak kW", "Avg kW", "Cost"] {
                html.push_str(&format!("<th style=\"{}\">{}</th>", TH_STYLE, h));
            }
            html.push_str("</tr>\n");
            for (i, row) in rows.iter().enumerate() {
                let bg = if i % 2 == 0 { ROW_EVEN } else { ROW_ODD };
                html.push_str(&format!("<tr style=\"background:{bg}\">"));
                html.push_str(&format!(
                    "<td style=\"{}\">{}</td>",
                    TD_STYLE,
                    escape_html(&row.label)
                ));
                html.push_str(&format!(
                    "<td style=\"{}text-align:right;\">{:.1}</td>",
                    TD_STYLE, row.consumption_kwh
                ));
                html.push_str(&format!(
                    "<td style=\"{}text-align:right;\">{:.1}</td>",
                    TD_STYLE, row.peak_kw
                ));
                html.push_str(&format!(
                    "<td style=\"{}text-align:right;\">{:.2}</td>",
                    TD_STYLE, row.avg_kw
                ));
                if row.cost > 0.0 {
                    html.push_str(&format!(
                        "<td style=\"{}text-align:right;\">{:.2}</td>",
                        TD_STYLE, row.cost
                    ));
                } else {
                    html.push_str(&format!(
                        "<td style=\"{}text-align:right;\">—</td>",
                        TD_STYLE
                    ));
                }
                html.push_str("</tr>\n");
            }
            html.push_str("</table>\n</div>\n");
        }

        RenderedSection::DemandSummary { title, rows } => {
            render_section_header(html, title);
            if rows.is_empty() {
                render_empty(html, "No demand data available.");
                return;
            }
            html.push_str(&format!("<table style=\"{}\">\n", TABLE_STYLE));
            html.push_str("<tr>");
            for h in &["Meter", "Peak kW", "Load Factor"] {
                html.push_str(&format!("<th style=\"{}\">{}</th>", TH_STYLE, h));
            }
            html.push_str("</tr>\n");
            for (i, row) in rows.iter().enumerate() {
                let bg = if i % 2 == 0 { ROW_EVEN } else { ROW_ODD };
                let lf_color = if row.load_factor > 0.7 {
                    "#27ae60"
                } else if row.load_factor > 0.4 {
                    "#e67e22"
                } else {
                    "#c0392b"
                };
                html.push_str(&format!("<tr style=\"background:{bg}\">"));
                html.push_str(&format!(
                    "<td style=\"{}\">{}</td>",
                    TD_STYLE,
                    escape_html(&row.label)
                ));
                html.push_str(&format!(
                    "<td style=\"{}text-align:right;\">{:.1}</td>",
                    TD_STYLE, row.peak_kw
                ));
                html.push_str(&format!("<td style=\"{}text-align:right;\"><span style=\"color:{lf_color};font-weight:600;\">{:.1}%</span></td>", TD_STYLE, row.load_factor * 100.0));
                html.push_str("</tr>\n");
            }
            html.push_str("</table>\n</div>\n");
        }
    }
}

// ----------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------

fn render_section_header(html: &mut String, title: &str) {
    html.push_str(&format!(
        "<div style=\"{}\">\n",
        "background:#16213e;border-radius:8px;padding:20px;margin-bottom:16px;border:1px solid #2a2a4a"
    ));
    html.push_str(&format!(
        "<h2 style=\"margin:0 0 12px 0;font-size:16px;color:#e0e0e0;border-bottom:1px solid #2a2a4a;padding-bottom:8px;\">{}</h2>\n",
        escape_html(title)
    ));
}

fn render_empty(html: &mut String, message: &str) {
    html.push_str(&format!(
        "<p style=\"color:#808090;font-style:italic;\">{}</p>\n</div>\n",
        escape_html(message)
    ));
}

fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn format_datetime(ms: i64) -> String {
    // Simple UTC datetime formatting without external crate
    let secs = ms / 1000;
    let days = secs / 86400;
    let time_secs = secs % 86400;
    let hours = time_secs / 3600;
    let mins = (time_secs % 3600) / 60;

    // Compute date from days since epoch (1970-01-01)
    let (year, month, day) = days_to_ymd(days);
    format!("{year:04}-{month:02}-{day:02} {hours:02}:{mins:02} UTC")
}

/// Convert days since Unix epoch to (year, month, day).
fn days_to_ymd(days: i64) -> (i64, i64, i64) {
    // Algorithm from Howard Hinnant's date library
    let z = days + 719468;
    let era = if z >= 0 { z } else { z - 146096 } / 146097;
    let doe = (z - era * 146097) as u64;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    let y = yoe as i64 + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    (y, m as i64, d as i64)
}

fn severity_color(severity: &str) -> &'static str {
    match severity.to_lowercase().as_str() {
        "life safety" | "lifesafety" => "#e74c3c",
        "critical" => "#e67e22",
        "warning" => "#f1c40f",
        "info" => "#3498db",
        _ => "#a0a0b0",
    }
}

// ---- Inline CSS constants ----

const TABLE_STYLE: &str = "width:100%;border-collapse:collapse;margin-bottom:4px;";
const TH_STYLE: &str = "padding:8px 12px;text-align:left;font-size:12px;color:#808090;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;border-bottom:1px solid #2a2a4a;";
const TD_STYLE: &str =
    "padding:6px 12px;font-size:13px;color:#d0d0e0;border-bottom:1px solid #1e1e3a;";
const ROW_EVEN: &str = "transparent";
const ROW_ODD: &str = "#1a1a30";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_escape_html() {
        assert_eq!(escape_html("<b>test</b>"), "&lt;b&gt;test&lt;/b&gt;");
        assert_eq!(escape_html("a & b"), "a &amp; b");
    }

    #[test]
    fn test_format_datetime() {
        // 2024-01-01 00:00 UTC
        let ts = 1704067200000_i64;
        let s = format_datetime(ts);
        assert!(s.contains("2024-01-01"));
        assert!(s.contains("00:00"));
    }

    #[test]
    fn test_render_empty_report() {
        let result = render_report_html(
            "Test Report",
            1704067200000,
            1704153600000,
            &TimeRangeKind::Last24Hours,
            &[],
        )
        .unwrap();
        assert!(result.contains("Test Report"));
        assert!(result.contains("Generated by OpenCrate BMS"));
        assert!(result.contains("<!DOCTYPE html>"));
    }

    #[test]
    fn test_render_history_summary() {
        let sections = vec![RenderedSection::HistorySummary {
            title: "Energy".to_string(),
            rows: vec![SummaryRow {
                label: "AHU-1/Power".to_string(),
                device_id: "ahu-1".to_string(),
                point_id: "power".to_string(),
                min: 10.5,
                max: 95.3,
                avg: 52.1,
                sample_count: 1440,
            }],
        }];
        let result = render_report_html(
            "Energy Report",
            1704067200000,
            1704153600000,
            &TimeRangeKind::Last24Hours,
            &sections,
        )
        .unwrap();
        assert!(result.contains("Energy"));
        assert!(result.contains("AHU-1/Power"));
        assert!(result.contains("10.50"));
        assert!(result.contains("95.30"));
    }
}
